pipeline {
  agent any

  tools {
    pip ''
  }

  stages{

    stage('clean WS') {
      steps {
        cleanWS()
      }
    }


    stage ('checkout') {
      steps {
      git branch: 'main', url: 'dsfsdfds.com'
      }
    }

    stage ('build') {
      steps {
        bat "pip install -r requiredment.txt"
      }
    }

  }
}
 
